apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
spec:
  destination:
    name: ''
    namespace: webapp
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops/kube_manifest
    repoURL: 'https://github.com/vaseemkhan007/node-app-gitops-github'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
